src/objects/Site_Event__c.object
<CustomObject>
    <description>Analytics event on a Force.com site (ie click, download)</description>
    <fields>
        <fullName>Action__c</fullName>
        <externalId>true</externalId>
        <label>Action</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <externalId>true</externalId>
        <label>Category</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Count__c</fullName>
        <label>Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <label>Site Event</label>
    <nameField>
        <label>Product</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Site Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Site_Metric__c.object
<CustomObject>
    <description>Single analytic metric for a Force.com site</description>
    <fields>
        <fullName>Metric__c</fullName>
        <description>Metric name from external system (ie Google Analytics)</description>
        <label>Metric</label>
        <picklist>
            <picklistValues>
                <fullName>ga:avgTimeOnSite</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ga:pageviewsPerVisit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ga:percentNewVisits</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ga:visitBounceRate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ga:visitLength</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ga:visitors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>mediaCodeConversion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>medicalInquirySource</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>sampleRequestPDF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>sampleRequestSource</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>savingsRequestSource</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Site_Metric_Date__c</fullName>
        <label>Site Metric Date</label>
        <referenceTo>Site_Metric_Date__c</referenceTo>
        <relationshipLabel>Site Metrics</relationshipLabel>
        <relationshipName>Site_Metrics</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Site Metric</label>
    <nameField>
        <label>Site Metric Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Site Metrics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Site_Metric_Date__c.object
<CustomObject>
    <description>Single date or date range of Force.com site analytics metric</description>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>End date for date ranges, null for single day</description>
        <inlineHelpText>End date for date ranges, empty for single day</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <inlineHelpText>Single date, or start date for date ranges</inlineHelpText>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Site Metric Date</label>
    <nameField>
        <label>Site Metric Date Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Site Metric Dates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Site_Metric_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Settings used for import Google Analytics data for a Force.com Site</description>
    <fields>
        <fullName>Email__c</fullName>
        <description>Email username for Google Analytics</description>
        <inlineHelpText>Email username for Google Analytics</inlineHelpText>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <description>Password for Google Analytics account</description>
        <inlineHelpText>Password for Google Analytics account</inlineHelpText>
        <label>Password</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Table_Id__c</fullName>
        <description>Google Table Id for Site, ie. ga:123456</description>
        <inlineHelpText>Google Table Id for Site, ie. ga:123456</inlineHelpText>
        <label>Table Id</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Site Metric Settings</label>
</CustomObject>

src/classes/ImportGoogleAnalytics.cls
/*
   Copyright 2011 Mavens Consulting, Inc.

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/   

public with sharing class ImportGoogleAnalytics {
	public static GoogleAnalytics ga;
	public static string singleMetricName = 'Test Single Metric';
	
	public static void importSingleMetric(string siteMetricSettingsName) {
		if(initialize(siteMetricSettingsName)) {	
			
			Site_Metric_Date__c metricDate = new Site_Metric_Date__c(Name = '2011 Q1', Start_Date__c = Date.newInstance(2011,1,1), 
				End_Date__c = Date.newInstance(2011,3,31));
				
			GoogleAnalytics.Entry entry = ga.getEntry(metricDate, new list<String>{GoogleAnalytics.VisitorsMetric});
			
			// only start inserts after all callouts are complete			
			insert metricDate;
			
			Site_Metric__c metric = new Site_Metric__c(Name = singleMetricName, Metric__c = GoogleAnalytics.VisitorsMetric, 
				Value__c = decimal.ValueOf(entry.getMetric(GoogleAnalytics.VisitorsMetric)), Site_Metric_Date__c = metricDate.Id);				
				
			insert metric;
		}		
	}
	
	public static void importDailyMetrics(string siteMetricSettingsName) {
		if(initialize(siteMetricSettingsName)) {		
			Date startDate = Date.newInstance(2011, 8, 19);
			Date endDate = Date.newInstance(2011, 8, 19);
		
			ga.insertDailyMetrics(startDate, endDate, new list<String>{GoogleAnalytics.VisitorsMetric,
										GoogleAnalytics.PageViewsPerVisitMetric,
										GoogleAnalytics.PercentNewVisitsMetric,
										GoogleAnalytics.VisitBounceRateMetric,
										GoogleAnalytics.AverageTimeOnSiteMetric});
		}
	}
	
	public static void importEvents(string siteMetricSettingsName) {
		if(initialize(siteMetricSettingsName)) {		
			Date startDate = Date.newInstance(2011, 2, 1);
			Date endDate = Date.newInstance(2011, 2, 2);
			List<String> metrics = new List<String>{GoogleAnalytics.TotalEventsMetric};			
			List<String> dimensions = new List<String>{GoogleAnalytics.DateDimension, GoogleAnalytics.EventCategoryDimension, 
				GoogleAnalytics.EventActionDimension, GoogleAnalytics.EventLabelDimension};
		
			list<GoogleAnalytics.Entry> entries = ga.getEntries(startDate, endDate, dimensions, metrics);
			list<Site_Event__c> events = new list<Site_Event__c>();
			
			for (GoogleAnalytics.Entry entry : entries) {
				Site_Event__c event = new Site_Event__c(
					Name = entry.getDimension(GoogleAnalytics.EventLabelDimension),
					Category__c = entry.getDimension(GoogleAnalytics.EventCategoryDimension),
					Action__c = entry.getDimension(GoogleAnalytics.EventActionDimension),
					Count__c = decimal.ValueOf(entry.getMetric(GoogleAnalytics.TotalEventsMetric)),
					Date__c = GoogleAnalytics.parseDate(entry.getDimension(GoogleAnalytics.DateDimension))
				);
				events.add(event);
			}
			
			insert events;
		}
	}
	
	static boolean initialize(string siteMetricSettingsName) {
		Site_Metric_Settings__c settings;
		
		try {
			settings = [Select s.Table_Id__c, s.Password__c, s.Email__c From Site_Metric_Settings__c s where s.Name = :siteMetricSettingsName];
		} catch (QueryException ex) {
			System.debug(Logginglevel.WARN, 'No Site Metric Settings with Name = ' + siteMetricSettingsName + '; stopping import');
			return false;
		}		

		ga = new GoogleAnalytics(settings);	
		return true;
	}	
}