src/objects/Site_Metric__c.object
<CustomObject>
    <description>Single analytic metric for a Force.com site</description>
    <fields>
        <fullName>Site_Metric_Date__c</fullName>
        <label>Site Metric Date</label>
        <referenceTo>Site_Metric_Date__c</referenceTo>
        <relationshipLabel>Site Metrics</relationshipLabel>
        <relationshipName>Site_Metrics</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Time__c</fullName>
        <description>Time value of metric in minutes:seconds</description>
        <inlineHelpText>Time value of metric in minutes:seconds</inlineHelpText>
        <label>Time</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Site Metric</label>
    <nameField>
        <label>Site Metric Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Site Metrics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Site_Metric_Date__c.object
<CustomObject>
    <description>Single date or date range of Force.com site analytics metric</description>
    <fields>
        <fullName>Start_Date__c</fullName>
        <inlineHelpText>Single date, or start date for date ranges</inlineHelpText>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Site Metric Date</label>
    <nameField>
        <label>Site Metric Date Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Site Metric Dates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SiteMetricTime_Test.cls
/*
   Copyright 2011 Mavens Consulting, Inc.

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/   

@isTest
private class SiteMetricTime_Test {
	static Site_Metric_Date__c metricDate = new Site_Metric_Date__c(Name = 'Test Date', Start_Date__c = Date.today());
	static Site_Metric__c metric = new Site_Metric__c(Name = 'Time Test');
	
	static {
		insert metricDate;
		metric.Site_Metric_Date__c = metricDate.Id;
	}

    static testMethod void secondsOnly() {
        metric.Value__c = 1;
        insert metric;
        System.assertEquals('00:01', getTime());
    }
    
    static testMethod void minutesAndSeconds() {
        metric.Value__c = 62;
        insert metric;
        System.assertEquals('01:02', getTime());
    }
    
    static testMethod void exceedMax() {
        metric.Value__c = 6000;
        insert metric;
        System.assertEquals('99:99', getTime());
    }
    
    static string getTime() {
    	return [select Time__c from Site_Metric__c where Id = :metric.id].Time__c; 
    }
}