src/objects/Site_Metric_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Settings used for import Google Analytics data for a Force.com Site</description>
    <fields>
        <fullName>Average_Time_on_Site__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Select if you want to track average time spent on the site per visit.</inlineHelpText>
        <label>Track Average Time on Site</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <description>Email username for Google Analytics</description>
        <inlineHelpText>Email username for Google Analytics</inlineHelpText>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <description>Password for Google Analytics account</description>
        <inlineHelpText>Password for Google Analytics account</inlineHelpText>
        <label>Password</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Table_Id__c</fullName>
        <description>Google Table Id for Site, ie. ga:123456</description>
        <inlineHelpText>Google Table Id for Site, ie. ga:123456</inlineHelpText>
        <label>Table Id</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Track_New_Visits__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Select if you want to track percentage of new visits.</inlineHelpText>
        <label>Track New Visits %</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Track_Page_Views_Per_Visit__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Select if you want to track page views per visit.</inlineHelpText>
        <label>Track Page Views Per Visit</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Track_Visit_Bounce_Rate__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Select if you want to track visit bounce rate.</inlineHelpText>
        <label>Track Visit Bounce Rate</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Track_Visitors__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Select if you want to track visitors to your site.</inlineHelpText>
        <label>Track Visitors</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Tracking_Average_Time_on_Site__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This is an internal field to determine if we need to pull just the day&apos;s Google Analytics data or last 30 day&apos;s worth Google Analytics data.</description>
        <label>Tracking Average Time on Site</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Tracking_New_Visits__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This is an internal field to determine if we need to pull just the day&apos;s Google Analytics data or last 30 day&apos;s worth Google Analytics data.</description>
        <label>Tracking New Visits %</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Tracking_Page_Views_Per_Visit__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This is an internal field to determine if we need to pull just the day&apos;s Google Analytics data or last 30 day&apos;s worth Google Analytics data.</description>
        <label>Tracking Page Views Per Visit</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Tracking_Visit_Bounce_Rate__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This is an internal field to determine if we need to pull just the day&apos;s Google Analytics data or last 30 day&apos;s worth Google Analytics data.</description>
        <label>Tracking Visit Bounce Rate</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Tracking_Visitors__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This is an internal field to determine if we need to pull just the day&apos;s Google Analytics data or last 30 day&apos;s worth Google Analytics data.</description>
        <label>Tracking Visitors</label>
        <type>Checkbox</type>
    </fields>
    <label>Site Metric Settings</label>
</CustomObject>

src/classes/AnalyticSettingsController_Test.cls
@isTest
private class AnalyticSettingsController_Test {
    static testMethod void testCancel() {
        AnalyticSettingsController asController = new AnalyticSettingsController();
        PageReference returnedPageRef = asController.cancel();
        System.assertEquals(returnedPageRef.getUrl(), Page.analyticsSettings.getUrl()); 
    }

    static testMethod void testSave() {
        AnalyticSettingsController asController = new AnalyticSettingsController();
        String siteName = 'MySite';
        
        asController.settings = new Site_Metric_Settings__c(Name = siteName, Email__c = 'as@as.com', Password__c = '123', Table_Id__c = 'ga:123456');
        asController.settings.Track_Visitors__c = false;
        asController.settings.Tracking_Visitors__c = true;
        asController.settings.Track_New_Visits__c = false;
        asController.settings.Tracking_New_Visits__c = true;
        asController.settings.Track_Page_Views_Per_Visit__c = false;
        asController.settings.Tracking_Page_Views_Per_Visit__c = true;
        asController.settings.Track_Visit_Bounce_Rate__c = false;
        asController.settings.Tracking_Visit_Bounce_Rate__c = true;
        asController.settings.Average_Time_on_Site__c = false;
        asController.settings.Tracking_Average_Time_on_Site__c = true;
        
        PageReference returnedPageRef = asController.save();
        
        Site_Metric_Settings__c  settings = [Select s.Name, s.Table_Id__c, s.Password__c, 
                               s.Email__c, s.Track_Visitors__c, s.Track_New_Visits__c, s.Track_Page_Views_Per_Visit__c, 
                               s.Track_Visit_Bounce_Rate__c, s.Average_Time_on_Site__c, 
                               s.Tracking_Visitors__c, s.Tracking_New_Visits__c, 
                               s.Tracking_Page_Views_Per_Visit__c, 
                               s.Tracking_Visit_Bounce_Rate__c, s.Tracking_Average_Time_on_Site__c
                          From Site_Metric_Settings__c s where s.Name = :siteName];
                          
        System.assertEquals(settings.Tracking_Visitors__c, false);
        System.assertEquals(settings.Tracking_New_Visits__c, false);
        System.assertEquals(settings.Tracking_Page_Views_Per_Visit__c, false);
        System.assertEquals(settings.Tracking_Visit_Bounce_Rate__c, false);
        System.assertEquals(settings.Tracking_Average_Time_on_Site__c, false);
        System.assertEquals(returnedPageRef.getUrl().contains('/apex/analyticssettings'), true);
    }
    static testMethod void testEditSite() { 
        AnalyticSettingsController asController = new AnalyticSettingsController();
        asController.siteName = 'JunkSite';
        
        PageReference returnedPageRef = asController.editSite();
        
        System.assertEquals(asController.settings.Name, 'JunkSite');
        System.assertEquals(returnedPageRef.getUrl().contains('/apex/editsite'), true);
    }
    
    static testMethod void testGetSiteInfo() { 
        AnalyticSettingsController asController = new AnalyticSettingsController();

        asController.siteName = '';
        PageReference returnedPageRef = asController.getSiteInfo();
        System.assertEquals(asController.settings, null);

        asController.siteName = 'AnotherJunkSite';
        returnedPageRef = asController.getSiteInfo();
        System.assertEquals(asController.settings, null);

        //Temporarily save a site info for testing
        String siteName = 'MySite';
        asController.settings = new Site_Metric_Settings__c(Name = siteName, Email__c = 'as@as.com', Password__c = '123', Table_Id__c = 'ga:123456');
        returnedPageRef = asController.save();
        asController.settings = null;

        //Verify that the settings are retrieved properly
        asController.siteName = 'MySite';
        returnedPageRef = asController.getSiteInfo();
        //System.assertNotEquals(asController.settings, null);
        System.assertNotEquals(null, asController.settings);
        System.assertEquals('123', asController.settings.Password__c);
        
        //Delete the settings record
        Site_Metric_Settings__c tempSettings = asController.settings;
        try {
            delete(tempSettings);
        } catch(System.DMLException e) {
        }
    }
    
    static testMethod void testSearchSites() { 
        AnalyticSettingsController asController = new AnalyticSettingsController();

        //zero value with wrong criteria
        asController.siteName = 'JunkSite';
        PageReference returnedPageRef = asController.searchSites();
        System.assertEquals(0, asController.sites.size());

        //One value with no criteria (as there is only one site defined in the database)
        asController.siteName = '';
        returnedPageRef = asController.searchSites();
        //System.assertEquals(1, asController.sites.size());
        //Temporarily save a site info for testing
        String siteName = 'MyBlog';
        asController.settings = new Site_Metric_Settings__c(Name = siteName, Email__c = 'as@as.com', Password__c = '123', Table_Id__c = 'ga:123456');
        returnedPageRef = asController.save();
        asController.settings = null;

        //One value with correct criteria
        asController.siteName = 'MyBlog';
        returnedPageRef = asController.searchSites();
        //System.assertEquals(1, asController.sites.size());
        System.assertEquals(1, asController.sites.size());
        
        //One value with no criteria (as there is only one site defined in the database)
        asController.siteName = '';
        returnedPageRef = asController.searchSites();
        System.assertEquals(1, asController.sites.size());
    }
}