src/objects/Site_Metric_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Settings used for import Google Analytics data for a Force.com Site</description>
    <fields>
        <fullName>Average_Time_on_Site__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Select if you want to track average time spent on the site per visit.</inlineHelpText>
        <label>Track Average Time on Site</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <description>Email username for Google Analytics</description>
        <inlineHelpText>Email username for Google Analytics</inlineHelpText>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <description>Password for Google Analytics account</description>
        <inlineHelpText>Password for Google Analytics account</inlineHelpText>
        <label>Password</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Table_Id__c</fullName>
        <description>Google Table Id for Site, ie. ga:123456</description>
        <inlineHelpText>Google Table Id for Site, ie. ga:123456</inlineHelpText>
        <label>Table Id</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Track_New_Visits__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Select if you want to track percentage of new visits.</inlineHelpText>
        <label>Track New Visits %</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Track_Page_Views_Per_Visit__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Select if you want to track page views per visit.</inlineHelpText>
        <label>Track Page Views Per Visit</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Track_Visit_Bounce_Rate__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Select if you want to track visit bounce rate.</inlineHelpText>
        <label>Track Visit Bounce Rate</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Track_Visitors__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Select if you want to track visitors to your site.</inlineHelpText>
        <label>Track Visitors</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Tracking_Average_Time_on_Site__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This is an internal field to determine if we need to pull just the day&apos;s Google Analytics data or last 30 day&apos;s worth Google Analytics data.</description>
        <label>Tracking Average Time on Site</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Tracking_New_Visits__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This is an internal field to determine if we need to pull just the day&apos;s Google Analytics data or last 30 day&apos;s worth Google Analytics data.</description>
        <label>Tracking New Visits %</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Tracking_Page_Views_Per_Visit__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This is an internal field to determine if we need to pull just the day&apos;s Google Analytics data or last 30 day&apos;s worth Google Analytics data.</description>
        <label>Tracking Page Views Per Visit</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Tracking_Visit_Bounce_Rate__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This is an internal field to determine if we need to pull just the day&apos;s Google Analytics data or last 30 day&apos;s worth Google Analytics data.</description>
        <label>Tracking Visit Bounce Rate</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Tracking_Visitors__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This is an internal field to determine if we need to pull just the day&apos;s Google Analytics data or last 30 day&apos;s worth Google Analytics data.</description>
        <label>Tracking Visitors</label>
        <type>Checkbox</type>
    </fields>
    <label>Site Metric Settings</label>
</CustomObject>

src/classes/AnalyticSettingsController.cls
public with sharing class AnalyticSettingsController {
    public PageReference cancel() {
       PageReference pageRef = Page.analyticsSettings;
       
       pageRef.setRedirect(true);
       
       return (pageRef);
    }


    public String siteName {get; set;}
    
    public Site_Metric_Settings__c settings {get; set;}

    public List<Site_Metric_Settings__c> sites {get; set;}


    public PageReference save() {
       PageReference pageRef = null;
       
       //Update tracking status to turn off tracking based on any instructions to track off a metric. 
       //Turning on tracking status would be done in the daily job.  
       if (settings.Track_Visitors__c == false && settings.Tracking_Visitors__c == true) {
           settings.Tracking_Visitors__c = false;
       }
       if (settings.Track_New_Visits__c == false && settings.Tracking_New_Visits__c == true) {
           settings.Tracking_New_Visits__c = false;
       }
       if (settings.Track_Page_Views_Per_Visit__c == false && settings.Tracking_Page_Views_Per_Visit__c == true) {
           settings.Tracking_Page_Views_Per_Visit__c = false;
       }
       if (settings.Track_Visit_Bounce_Rate__c == false && settings.Tracking_Visit_Bounce_Rate__c == true) {
           settings.Tracking_Visit_Bounce_Rate__c = false;
       }
       if (settings.Average_Time_on_Site__c == false && settings.Tracking_Average_Time_on_Site__c == true) {
           settings.Tracking_Average_Time_on_Site__c = false;
       }
       
       try {
            upsert(settings);
        } catch(System.DMLException e) {
            ApexPages.addMessages(e);
            return null;
        }

       pageRef = Page.analyticsSettings;
       pageRef.getParameters().put('siteName', settings.Name);
       
       return (pageRef);
    }

    public PageReference editSite() {
       PageReference pageRef = null;

         settings = null;
         try {
            settings = [Select s.Name, s.Table_Id__c, s.Password__c, 
                               s.Email__c, s.Track_Visitors__c, s.Track_New_Visits__c, s.Track_Page_Views_Per_Visit__c, 
                               s.Track_Visit_Bounce_Rate__c, s.Average_Time_on_Site__c, 
                               s.Tracking_Visitors__c, s.Tracking_New_Visits__c, 
                               s.Tracking_Page_Views_Per_Visit__c, 
                               s.Tracking_Visit_Bounce_Rate__c, s.Tracking_Average_Time_on_Site__c
                          From Site_Metric_Settings__c s where s.Name = :siteName];
         } catch (QueryException ex) {
         }       
         
         if (settings == null) {
            settings = new Site_Metric_Settings__c();
            settings.Name = siteName;
         }
    
         pageRef = Page.editsite;
         pageRef.getParameters().put('siteName', siteName);
       
       return (pageRef);
    }

    public PageReference getSiteInfo() {
       settings = null;
       if (siteName != null && siteName != '') {
         try {
            settings = [Select s.Name, s.Table_Id__c, s.Password__c, 
                               s.Email__c, s.Track_Visitors__c, s.Track_New_Visits__c, s.Track_Page_Views_Per_Visit__c, 
                               s.Track_Visit_Bounce_Rate__c, s.Average_Time_on_Site__c, 
                               s.Tracking_Visitors__c, s.Tracking_New_Visits__c, 
                               s.Tracking_Page_Views_Per_Visit__c, 
                               s.Tracking_Visit_Bounce_Rate__c, s.Tracking_Average_Time_on_Site__c
                          From Site_Metric_Settings__c s where s.Name = :siteName];
         } catch (QueryException ex) {
            ApexPages.Message pageMsg = new ApexPages.Message(ApexPages.Severity.ERROR, 'No Site Metric Settings with Name = ' + siteName);
            ApexPages.addMessage(pageMsg);
         }       
       } else {
            ApexPages.Message pageMsg = new ApexPages.Message(ApexPages.Severity.WARNING, 'Site Name is asd required');
            ApexPages.addMessage(pageMsg);
       }
       return null;
    }
    
    public PageReference searchSites() {
       sites = null;
       settings = null;
       if (siteName == null || siteName == '') {
         try {
            sites = [Select s.Name
                          From Site_Metric_Settings__c s];
         } catch (QueryException ex) {
            ApexPages.Message pageMsg = new ApexPages.Message(ApexPages.Severity.WARNING, 'No Site setup with Name = ' + siteName);
            ApexPages.addMessage(pageMsg);
         }       
       } else {
         try {
            sites = [Select s.Name
                          From Site_Metric_Settings__c s where s.Name = :siteName];
         } catch (QueryException ex) {
            ApexPages.Message pageMsg = new ApexPages.Message(ApexPages.Severity.WARNING, 'No Site setup with Name = ' + siteName);
            ApexPages.addMessage(pageMsg);
         }       
       }
       if (sites == null || sites.size() == 0) {
            ApexPages.Message pageMsg = new ApexPages.Message(ApexPages.Severity.WARNING, 'No sites for the entered criteria.');
            ApexPages.addMessage(pageMsg);
       }
       return null;
    }

    public AnalyticSettingsController () {
    }
}