src/objects/Site_Event__c.object
<CustomObject>
    <description>Analytics event on a Force.com site (ie click, download)</description>
    <label>Site Event</label>
    <nameField>
        <label>Product</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Site Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Site_Metric__c.object
<CustomObject>
    <description>Single analytic metric for a Force.com site</description>
    <label>Site Metric</label>
    <nameField>
        <label>Site Metric Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Site Metrics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Site_Metric_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Settings used for import Google Analytics data for a Force.com Site</description>
    <fields>
        <fullName>Email__c</fullName>
        <description>Email username for Google Analytics</description>
        <inlineHelpText>Email username for Google Analytics</inlineHelpText>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <description>Password for Google Analytics account</description>
        <inlineHelpText>Password for Google Analytics account</inlineHelpText>
        <label>Password</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Table_Id__c</fullName>
        <description>Google Table Id for Site, ie. ga:123456</description>
        <inlineHelpText>Google Table Id for Site, ie. ga:123456</inlineHelpText>
        <label>Table Id</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Site Metric Settings</label>
</CustomObject>

src/classes/ImportGoogleAnalytics_Test.cls
/*
   Copyright 2011 Mavens Consulting, Inc.

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/   

@isTest
private class ImportGoogleAnalytics_Test {
	static string siteMetricSettingsName = 'Test';
	
	static {
		insert new Site_Metric_Settings__c(Name='Test', Email__c='test@test.com', Password__c='test', Table_Id__c='test');
	}
	
	static testMethod void importSingleMetricSavesMetrics() {
        //Temporarily save a site info for testing
   	    AnalyticSettingsController asController = new AnalyticSettingsController();
        asController.settings = new Site_Metric_Settings__c(Name = siteMetricSettingsName, Email__c = 'as@as.com', Password__c = '123', Table_Id__c = 'ga:123456');
        PageReference returnedPageRef = asController.save();
        asController.settings = null;

		ImportGoogleAnalytics.importSingleMetric(siteMetricSettingsName);
		System.assert([select count() from Site_Metric__c where Name = :ImportGoogleAnalytics.singleMetricName] > 0);
	}

	static testMethod void importDailyMetricsSavesMetrics() {
        //Temporarily save a site info for testing
   	    AnalyticSettingsController asController = new AnalyticSettingsController();
        asController.settings = new Site_Metric_Settings__c(Name = siteMetricSettingsName, Email__c = 'as@as.com', Password__c = '123', Table_Id__c = 'ga:123456');
        PageReference returnedPageRef = asController.save();
        asController.settings = null;

		ImportGoogleAnalytics.importDailyMetrics(siteMetricSettingsName);
		System.assert([select count() from Site_Metric__c] > 0);
	}
	
	static testMethod void importEventsSavesEvents() {
        //Temporarily save a site info for testing
   	    AnalyticSettingsController asController = new AnalyticSettingsController();
        asController.settings = new Site_Metric_Settings__c(Name = siteMetricSettingsName, Email__c = 'as@as.com', Password__c = '123', Table_Id__c = 'ga:123456');
        PageReference returnedPageRef = asController.save();
        asController.settings = null;

		ImportGoogleAnalytics.importEvents(siteMetricSettingsName);
		System.assert([select count() from Site_Event__c] > 0);		
	}
	
}